# Generated by Django 4.2.16 on 2024-11-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='medicine_scans/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed_scans/')),
                ('detections', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
