# Generated by Django 4.2.16 on 2024-11-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0002_medicinescan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineScan',
        ),
    ]
